#!/bin/bash

pacman -Qqent > ~/Maintenance/packages/native.txt

pacman -Qqn > ~/Maintenance/packages/native-extended.txt

pacman -Qqm > ~/Maintenance/packages/foreign.txt

tar -zcvf "~/Maintenance/packages/backup_$(date --iso-8601)" ~/Maintenance/packages/*.txt
