#!/bin/bash

pacman -Qqent > ~/Maintenance/packages/native.txt

pacman -Qqn > ~/Maintenance/packages/native-extended.txt

pacman -Qqm > ~/Maintenance/packages/foreign.txt

cd "$HOME/Maintenance/packages"

tar -zcvf "backup_$(date --iso-8601)" *.txt
